title: Phuong Tran
logo: https://github.com/phuongdtrn/Phuong_Portfolio/blob/main/images/profilepic.jpg
description: Hi! I'm an analytics professional who has a strong passion for delivering business insights and creating product innovation through the power of data. Currently, I'm a candidate for the Master of Science in Business Analytics at the University of Minnesota, Carlson School of Management.
show_downloads: false
theme: jekyll-theme-minimal
