logo: https://media-exp1.licdn.com/dms/image/C5603AQH-JHeTjFi7uA/profile-displayphoto-shrink_400_400/0/1651439248750?e=1657152000&v=beta&t=rvBCmZUieDHAvfGjGX7-27YA6SJAIubzFwg2y5uDodQ
title: Phuong Tran
description: Hi! I'm an analytics professional who has a strong passion for delivering business insights and creating product innovation through the power of data. Currently, I'm a candidate for the Master of Science in Business Analytics at the University of Minnesota, Carlson School of Management.
show_downloads: false
