title: Phuong Tran
logo: https://drive.google.com/file/d/1h0EwVZ07b1oBHOZ0inr-0fck83cYtwIf/view
description: Hi. I'm an analytics professional with 2 years of experience who has strong passion for delivering business insights and creating product innovation through the power of data. Currently, I'm a candidate for the Master of Science in Business Analytics at the University of Minnesota, Carlson School of Management.
show_downloads: false
theme: jekyll-theme-minimal
